#!/bin/bash

[ $(pidof -sx sxhkd) ] || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          15
bspc config bottom_padding	-5
bspc config left_padding	15
bspc config right_padding	15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focus_by_distance	true

[ $(pidof -sx hsetroot) ] || hsetroot -cover ~/Pictures/back.jpg
[ $(pidof -sx compton) ] || compton -b --respect-prop-shadow
killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 0.25; done
polybar mybar -r &
setxkbmap -layout us
setxkbmap -option 'grp:alt_shift_toggle'

bspc rule -a Eog floating=on
bspc rule -a Ghidra floating=on
bspc rule -a anbox floating=on
bspc rule -a Firefox focus=on
bspc rule -a libreoffice* focus=on

wmname LG3D
